packages:
  - client/
  - server/
  - e2e/
allowBuilds:
  core-js: true
  bcrypt: true
  esbuild: true
  rollup: true
  sqlite3: true
  negaposi-analyzer-ja: true
  ffmpeg-static: true
  sharp: true
saveExact: true
shellEmulator: true
